language: node_js
install: "npm install"
before_script: "./node_modules/.bin/cake test-prepare"
script: "./node_modules/.bin/cake test"
node_js:
  - "0.8"
  - "0.10"
notifications:
  irc:
    - "irc.squirrel.org"
  email:
    recipients:
      - mattheyj@gmail.com